name: meshagent-ubuntucore
version: '0.2'
summary: MeshCentral Agent for Ubuntu Core
description: |
  Adds a MeshCentral agent for remote access to Ubuntu Core devices.
confinement: devmode
grade: stable

apps:
  meshagent-ubuntucore:
    command: meshinstall.sh
        
  meshagent-ubuntucore-service:
    command: meshservice.sh
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 5s

parts:
  meshagent-ubuntucore:
    source: meshsource/
    plugin: dump
